function vertical_clear_configuration -d 'Clear vertical prompt configuration'
  set -eU vertical_cue
  set -eU vertical_cue_color
  set -eU vertical_dir_color
  set -eU vertical_dir_prefix
  set -eU vertical_dir_prefix_color
  set -eU vertical_dir_trunc_git
  set -eU vertical_dir_trunc_home
  set -eU vertical_duration_color
  set -eU vertical_duration_min
  set -eU vertical_duration_prefix
  set -eU vertical_duration_prefix_color
  set -eU vertical_git_branch_color
  set -eU vertical_git_branch_prefix
  set -eU vertical_git_branch_prefix_color
  set -eU vertical_git_status_color
  set -eU vertical_git_status_prefix
  set -eU vertical_git_status_prefix_color
  set -eU vertical_git_status_suffix
  set -eU vertical_git_status_suffix_color
  set -eU vertical_git_status_sym_added
  set -eU vertical_git_status_sym_added_deleted
  set -eU vertical_git_status_sym_ahead
  set -eU vertical_git_status_sym_behind
  set -eU vertical_git_status_sym_deleted
  set -eU vertical_git_status_sym_diverged
  set -eU vertical_git_status_sym_modified
  set -eU vertical_git_status_sym_renamed
  set -eU vertical_git_status_sym_stashed
  set -eU vertical_git_status_sym_unmerged
  set -eU vertical_git_status_sym_untracked
  set -eU vertical_host_color
  set -eU vertical_host_prefix
  set -eU vertical_host_prefix_color
  set -eU vertical_host_ssh_only
  set -eU vertical_jobs_color
  set -eU vertical_jobs_prefix
  set -eU vertical_jobs_prefix_color
  set -eU vertical_jobs_sym
  set -eU vertical_newline
  set -eU vertical_order
  set -eU vertical_user_color
  set -eU vertical_user_prefix
  set -eU vertical_user_prefix_color
  set -eU vertical_user_ssh_only
  set -eU vertical_vert_bottom
  set -eU vertical_vert_color_failure
  set -eU vertical_vert_color_success
  set -eU vertical_vert_top
  set -eU vertical_vi_mode_color
  set -eU vertical_vi_mode_prefix
  set -eU vertical_vi_mode_prefix_color
  set -eU vertical_vi_mode_sym_insert
  set -eU vertical_vi_mode_sym_normal
  set -eU vertical_vi_mode_sym_replace_one
  set -eU vertical_vi_mode_sym_visual

  true # Always exit successfully
end
